### ISSUE TITLE
I changed the scale value, but I can't see the difference

### ISSUE THREAD

**Issue by EasiestSoft** [chrisww/watermark#2]
Is it similar to the scale option in https://github.com/Eun/watermark

**Comment by cww0614** [comment]
`scale` scales the font size as well as the space between text. If you just want to scale the text itself, `font-size` option shoud suffice.

It is a bug though that `scale` doesn't work, and it should be fixed now.

**Comment by EasiestSoft** [comment]
Fixed!
Thanks for your quick response
