### ISSUE TITLE
Is it possible to add lanczos3 sampling filter to adjust the image size

### ISSUE THREAD

**Issue by EasiestSoft** [chrisww/watermark#3]
When I use the option `-- output-dpi` to adjust the image size, the output image quality is not very good compared to other tools that implement the lanczos3 sampling filter
Currently, I have to use other tools to resize the image for better quality

Is it possible to add lanczos3 sampling filter to adjust the image size in the future?

The tools I used to resize the image:

https://github.com/libvips/libvips
https://github.com/foresterre/sic

**Comment by cww0614** [comment]
It's an interesting feature to add and now added by 41ae1d6f2cbc67f9ba35c15d7e98797d4f27a233!

By the way, I also removed the `--output-dpi` option and added a `--resize` option instead. Changing output dpi seems to only scale the image and the name is rather unituitive for this sole functionality.

**Comment by EasiestSoft** [comment]
Thank you very much
I tested the resize function, the image quality after resize is good
