### ISSUE TITLE
Can I specify the output image

### ISSUE THREAD

**Issue by EasiestSoft** [chrisww/watermark#4]
The default output image is similar to _in.watermarked.png_

Sometimes I want apply the effects to the input image, it would be better if the _output_ option is available

**Comment by cww0614** [comment]
Thanks for the suggestion, this is now added in 4efecef57e93ff23b30ba28f1ac5c43e1b08a1de

**Comment by EasiestSoft** [comment]
Great!
I tested the _--output_ option, it works
